# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShelfMagnetic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShelfMagnetic
    pod 'AFNetworking'
    pod 'MJRefresh'

  target 'ShelfMagneticTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShelfMagneticUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
